=== ai-weline/WelineFramework/app/code/Weline/Backend/etc/xsd/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:weline:module:Weline_Backend::etc/xsd/menu.xsd"
           elementFormDefault="qualified"
           version="0.0.1">
    <xs:element name="menus">
        <xs:annotation>
            <xs:documentation>
                系统菜单
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="add" type="menuDeclaration" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
<!--    菜单声明-->
    <xs:complexType name="menuDeclaration">
        <xs:annotation>
            <xs:documentation>
                Menu declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="source" type="xs:integer" use="required"/>
        <xs:attribute name="title" type="xs:string" use="required"/>
        <xs:attribute name="action" type="xs:string" use="required"/>
        <xs:attribute name="parent" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== ai-weline/WelineFramework/app/code/Weline/Backend/etc/backend/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menus xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="urn:weline:module:Weline_Backend::etc/xsd/menu.xsd"
       xs:schemaLocation="urn:weline:module:Weline_Backend::etc/xsd/menu.xsd">
    <!--顶层：系统-->
    <add source="Weline_Backend::system_menu" name="system_menu" title="系统" action="" parent="" icon="" order="0"/>
    <add source="Weline_Backend::system_dashboard" name="system_dashboard" title="面板" action="/"
         parent="Weline_Backend::system_menu" icon="mdi mdi-desktop-mac-dashboard" order="1"/>
    <!--菜单管理-->
    <add source="Weline_Backend::system_menus" name="system_menus" title="菜单管理" action="/menus"
         parent="Weline_Backend::system_menu" icon="ri-menu-line" order="100"/>
    <!--内容管理-->
    <add source="Weline_Backend::system_cms" name="system_cms" title="内容管理" action="/cms"
         parent="Weline_Backend::system_menu" icon="ri-edit-box-line" order="200"/>

    <!--顶层：系统配置-->
    <add source="Weline_Backend::system_configuration" name="system_configuration" title="系统配置" action="" parent=""
         icon="" order="10000"/>
    <!--事件管理-->
    <add source="Weline_Backend::system_events" name="system_events" title="事件管理" action="/events"
         parent="Weline_Backend::system_configuration" icon="ri-spy-fill" order="10100"/>
    <!--插件管理-->
    <add source="Weline_Backend::system_plugins" name="system_plugins" title="插件管理" action="/plugins"
         parent="Weline_Backend::system_configuration" icon="ri-plug-2-line" order="10200"/>
    <!--模组管理-->
    <add source="Weline_Backend::system_modules" name="system_modules" title="模组管理" action="/modules"
         parent="Weline_Backend::system_configuration" icon="ri-sound-module-line" order="10300"/>
</menus>

=== ai-weline/WelineFramework/app/code/Weline/Admin/etc/backend/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menus xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="urn:weline:module:Weline_Backend::etc/xsd/menu.xsd"
       xs:schemaLocation="urn:weline:module:Weline_Backend::etc/xsd/menu.xsd">
    <!--系统-->
    <!--系统-面板-->
    <add source="Weline_Admin::system_dashboard" name="system_dashboard" title="面板" action="admin"
         parent="Weline_Backend::system_menu" icon="mdi mdi-desktop-mac-dashboard" order="1"/>
    <!--系统-用户-->
    <add source="Weline_Admin::system_user" name="system_user" title="管理员" action="admin/backend/user/listing"
         parent="Weline_Backend::system_menu" icon="fas fa-user-shield" order="2"/>
    <add source="Weline_Admin::system_user_listing" name="system_user_listing" title="用户" action="admin/backend/user/listing"
         parent="Weline_Admin::system_user" icon="fas fa-users-cog" order="1"/>
    <add source="Weline_Admin::system_user_assign_role" name="system_user_assign_role" title="角色归配" action="admin/backend/user/assignRole"
         parent="Weline_Admin::system_user" icon="ri-shield-keyhole-line" order="2"/>
    <!--菜单管理-->
    <add source="Weline_Admin::system_menu_manager" name="system_menu_manager" title="菜单管理" action="admin/system/menus"
         parent="Weline_Backend::system_menu" icon="ri-menu-line" order="100"/>
    <!--内容管理-->
    <add source="Weline_Admin::system_cms" name="system_cms" title="内容管理" action="admin/system/cms"
         parent="Weline_Backend::system_menu" icon="ri-edit-box-line" order="200"/>

    <!--事件管理-->
    <add source="Weline_Admin::system_events" name="system_events" title="事件管理" action="admin/system/events"
         parent="Weline_Backend::system_configuration" icon="ri-spy-fill" order="10100"/>
    <!--插件管理-->
    <add source="Weline_Admin::system_plugins" name="system_plugins" title="插件管理" action="admin/system/plugins"
         parent="Weline_Backend::system_configuration" icon="ri-plug-2-line" order="10200"/>
    <!--路由管理-->
    <add source="Weline_Admin::system_modules_router" name="system_modules_router" title="路由管理" action="admin/system/modules/router"
         parent="Weline_Backend::system_configuration" icon="mdi mdi-router" order="10500"/>
    <!--开发工具-->
    <add source="Weline_Admin::origin_template" name="origin-template" title="后端模板库" action="admin/template"
         parent="Weline_Backend::system_dev_configuration" icon="mdi mdi-view-module" order="20002"/>
    <add source="Weline_Admin::template_upzet" name="template_upzet" title="Upzet" action="admin/template/upzet"
         parent="Weline_Admin::origin_template" icon="mdi mdi-file-document-multiple" order="200021"/>
</menus>
